{
 "title": "Load Test - {test_number}",
 "tags": [ "templated" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_node_labels{label_execution_id=\"{test_number}\"})"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{job=\"kube-state-metrics\", namespace=\"selenium\", phase=\"Running\"})"
    }
   ]
  },
  {
   "title": "Pending Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{job=\"kube-state-metrics\", namespace=\"selenium\", phase=\"Pending\"})"
    }
   ]
  },
  {
   "title": "Failed Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{job=\"kube-state-metrics\", namespace=\"selenium\", phase=\"Failed\"})"
    }
   ]
  },
  {
   "title": "Chrome Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_labels{pod=~\"chrome-.*\", label_execution_id=\"{test_number}\"})"
    }
   ]
  },
  {
   "title": "Firefox Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_labels{pod=~\"firefox-.*\", label_execution_id=\"{test_number}\"})"
    }
   ]
  },
  {
   "title": "Cluster Node MEM Available",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job)(rate(node_memory_MemFree_bytes{instance=~\".*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Cluster Node CPU Bandwidth",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job)(rate(node_cpu_seconds_total{instance=~\".*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Cluster Network Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_fifo_total[1m])"
    }
   ]
  },
  {
   "title": "Chrome MEM Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  kube_pod_labels{label_execution_id=~\"{test_number}\"} * on (pod) group_right(label_execution_id) container_memory_usage_bytes{namespace=\"selenium\", container=\"chrome\"}\n  ) \n  by (label_execution_id)"
    }
   ]
  },
  {
   "title": "Chrome CPU Average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  kube_pod_labels{label_execution_id=~\"{test_number}\"} * on (pod) group_right(label_execution_id) rate(container_cpu_load_average_10s{namespace=\"selenium\", container=\"chrome\"}[1m])\n  )\n  by (label_execution_id)"
    }
   ]
  },
  {
   "title": "Firefox MEM Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  kube_pod_labels{label_execution_id=~\"{test_number}\"} * on (pod) group_right(label_execution_id) container_memory_usage_bytes{namespace=\"selenium\", container=\"firefox\"}\n  ) \n  by (label_execution_id)"
    }
   ]
  },
  {
   "title": "Firefox CPU Average",
   "type": "graph",
   "description": "Chrome",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  kube_pod_labels{label_execution_id=~\"{test_number}\"} * on (pod) group_right(label_execution_id) rate(container_cpu_load_average_10s{namespace=\"selenium\", container=\"firefox\"}[1m])\n  )\n  by (label_execution_id)"
    }
   ]
  },
  {
   "title": "Chrome MEM Max Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  kube_pod_labels{label_execution_id=~\"{test_number}\"} * on (pod) group_right(label_execution_id) container_memory_max_usage_bytes{namespace=\"selenium\", container=\"chrome\"}\n  ) \n  by (label_execution_id)"
    }
   ]
  },
  {
   "title": "Chrome Network Bytes Transmited",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  kube_pod_labels{label_execution_id=~\"{test_number}\"} * on (pod) group_right(label_execution_id) rate(container_network_transmit_bytes_total{namespace=\"selenium\", container=\"chrome\"}[1m])\n  )\n  by (label_execution_id)"
    }
   ]
  },
  {
   "title": "Firefox MEM Max Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  kube_pod_labels{label_execution_id=~\"{test_number}\"} * on (pod) group_right(label_execution_id) container_memory_max_usage_bytes{namespace=\"selenium\", container=\"firefox\"}\n  ) \n  by (label_execution_id)"
    }
   ]
  },
  {
   "title": "Firefox Network Bytes Transmited",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  kube_pod_labels{label_execution_id=~\"{test_number}\"} * on (pod) group_right(label_execution_id) rate(container_network_transmit_bytes_total{namespace=\"selenium\", container=\"firefox\"}[1m])\n  )\n  by (label_execution_id)"
    }
   ]
  },
  {
   "title": "Chrome CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  kube_pod_labels{label_execution_id=~\"{test_number}\"} * on (pod) group_right(label_execution_id) rate(container_cpu_usage_seconds_total{namespace=\"selenium\", container=\"chrome\"}[1m])\n  )\n  by (label_execution_id)",
     "panelId": 36
    }
   ]
  },
  {
   "title": "Chrome MEM Failure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  kube_pod_labels{label_execution_id=~\"{test_number}\"} * on (pod) group_right(label_execution_id) rate(container_memory_failures_total{namespace=\"selenium\", container=\"chrome\"}[1m])\n  )\n  by (label_execution_id)"
    }
   ]
  },
  {
   "title": "Firefox CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  kube_pod_labels{label_execution_id=~\"{test_number}\"} * on (pod) group_right(label_execution_id) rate(container_cpu_usage_seconds_total{namespace=\"selenium\", container=\"firefox\"}[1m])\n  )\n  by (label_execution_id)"
    }
   ]
  },
  {
   "title": "Firefox MEM Failure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  kube_pod_labels{label_execution_id=~\"{test_number}\"} * on (pod) group_right(label_execution_id) rate(container_memory_failures_total{namespace=\"selenium\", container=\"firefox\"}[1m])\n  )\n  by (label_execution_id)"
    }
   ]
  }
 ]
}