{
 "title": "Load Test",
 "tags": [ "templated" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Node by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_node_status_allocatable{resource=\"memory\"}"
    }
   ]
  },
  {
   "title": "Pods per Cluster",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (kube_namespace_name) (kube_pod_info)"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=\"true\"}==1)"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\"}[30m]) - on (namespace,pod,container) group_left avg by (namespace,pod,container)(kube_pod_container_resource_requests{resource=\"cpu\"})) * -1 >0)"
    }
   ]
  },
  {
   "title": "Pods Restarted",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(kube_cluster_name, kube_namespace_name)(changes(kube_pod_status_ready{condition=\"true\"}[1m]))"
    }
   ]
  },
  {
   "title": "MEM Idle",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((container_memory_usage_bytes{container!=\"POD\",container!=\"\"} - on (namespace,pod,container) avg by (namespace,pod,container)(kube_pod_container_resource_requests{resource=\"memory\"})) * -1 >0 ) / (1024*1024*1024)"
    }
   ]
  },
  {
   "title": "Container - CPU Total Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total[1m]))"
    }
   ]
  },
  {
   "title": "Cluster CPU Bandwidth",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum (node_cpu_seconds_total)" }
   ]
  },
  {
   "title": "Pod Name - CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod_name) (rate(container_cpu_usage_seconds_total{namespace=\"default\"}[1m]))"
    }
   ]
  },
  {
   "title": "Container - CPU Load Average",
   "type": "graph",
   "description": "Namespace Default",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_load_average_10s{namespace=\"default\"}[1m])"
    }
   ]
  },
  {
   "title": "Container - CPU Usage",
   "type": "graph",
   "description": "Namespace Default",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"default\"}[1m])"
    }
   ]
  },
  {
   "title": "NGinx Pods",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_labels{exported_pod=~\"nginx-.*\"})"
    }
   ]
  }
 ]
}