{
 "title": "Load Test - {test_number}",
 "tags": [ "templated" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "Pods per Cluster",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (kube_namespace_name) (kube_pod_info)"
    }
   ]
  },
  {
   "title": "Nodes per Cluster",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\", status=\"true\"}==1)"
    }
   ]
  },
  {
   "title": "Total Pods Running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{job=\"kube-state-metrics\", namespace=\"selenium\", phase=\"Running\", label_execution_id=\"{test_number}\"})"
    }
   ]
  },
  {
   "title": "Chrome Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_labels{pod=~\"chrome-.*\", label_execution_id=\"{test_number}\"})"
    }
   ]
  },
  {
   "title": "Firefox Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_labels{pod=~\"firefox-.*\", label_execution_id=\"{test_number}\"})"
    }
   ]
  },
  {
   "title": "Container MEM Max Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(container_memory_max_usage_bytes{label_execution_id=\"{test_number}\"}[1m]))"
    }
   ]
  },
  {
   "title": "Container - MEM Failure",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(container_memory_failures_total{label_execution_id=\"{test_number}\"}[1m]))"
    }
   ]
  },
  {
   "title": "Cluster Node MEM Available",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job)(rate(node_memory_MemFree_bytes{instance=~\".*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Cluster Node CPU Bandwidth",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job)(rate(node_cpu_seconds_total{instance=~\".*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Cluster CPU Idle",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\"}[5m]) - on (namespace,pod,container) group_left avg by (namespace,pod,container)(kube_pod_container_resource_requests{resource=\"cpu\"})) * -1 >0)"
    }
   ]
  },
  {
   "title": "Cluster MEM Idle",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((container_memory_usage_bytes{container!=\"POD\",container!=\"\"} - on (namespace,pod,container) avg by (namespace,pod,container)(kube_pod_container_resource_requests{resource=\"memory\"})) * -1 >0 ) / (1024*1024*1024)"
    }
   ]
  },
  {
   "title": "Firefox MEM Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_max_usage_bytes{pod=~\"firefox-.*\", label_execution_id=\"{test_number}\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Firefox CPU Average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(rate(container_cpu_load_average_10s{pod=~\"firefox-.*\", label_execution_id=\"{test_number}\"}[1m]))"
    }
   ]
  },
  {
   "title": "Container - CPU Load Average",
   "type": "graph",
   "description": "Namespace Default",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_load_average_10s{namespace=\"default\"}[1m])"
    }
   ]
  },
  {
   "title": "Selenium NS CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod_name) (rate(container_cpu_usage_seconds_total{namespace=\"selenium\"}[1m]))"
    }
   ]
  },
  {
   "title": "Chrome MEM Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_max_usage_bytes{pod=~\"chrome-.*\", label_execution_id=\"{test_number}\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Chrome CPU Average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(rate(container_cpu_load_average_10s{pod=~\"chrome-.*\", label_execution_id=\"{test_number}\"}[1m]))",
     "panelId": 36
    }
   ]
  },
  {
   "title": "Container CPU Usage - Selenium",
   "type": "graph",
   "description": "Namespace Selenium",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"selenium\"}[1m])"
    }
   ]
  },
  {
   "title": "Cluster Network Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_fifo_total[1m])"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\"}[1m]) - on (namespace,pod,container) group_left avg by (namespace,pod,container)(kube_pod_container_resource_requests{resource=\"memory\"})) * -1 >0)"
    }
   ]
  },
  {
   "title": "Execution_Id - {test_number}",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_labels{label_execution_id=\"{test_number}\"})"
    }
   ]
  },
  {
   "title": "Execution_Id - Teste_02",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_labels{label_execution_id=\"{test_number}\"})"
    }
   ]
  }
 ]
}