# eks_cluster.yaml
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: service-monitoring-cluster
  region: us-east-1
  version: "1.19"
managedNodeGroups:
  - name: monitoring-ng
    instanceType: t3.medium
    minSize: 2
    maxSize: 4
    desiredCapacity: 2 
    volumeSize: 20
    labels: {execution_id: test_01}
